config/routes.rb
Print::Application.routes.draw do

  resources :printers
  root :to => redirect('/printers')

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Bootstrap Template
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'bootstrap.css'
    = stylesheet_link_tag 'bootstrap-responsive.css'

    =csrf_meta_tags

  %body
    %div.navbar.navbar-inverse.navbar-fixed-top{:role => 'navigation'}
      %div.navbar-inner
        %div.container
          %button.btn-navbar{:type => 'button', 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => '#'} Project Name
          %div.nav-collapse.collapse
            %ul.nav
              %li{:class => "#{'active' if current_page?(printers_path)}"}
                %a{:href => root_path} Home
              %li
                %a{:href => '#'} About
              %li
                %a{:href => '#'} Contact
    = yield

  = javascript_include_tag 'bootstrap'
  = javascript_include_tag 'bootstrap-transition'
  = javascript_include_tag 'bootstrap-alert'
  = javascript_include_tag 'bootstrap-modal'
  = javascript_include_tag 'bootstrap-dropdown'
  = javascript_include_tag 'bootstrap-scrollspy'
  = javascript_include_tag 'bootstrap-tab'
  = javascript_include_tag 'bootstrap-tooltip'
  = javascript_include_tag 'bootstrap-popover'
  = javascript_include_tag 'bootstrap-button'
  = javascript_include_tag 'bootstrap-collapse'
  = javascript_include_tag 'bootstrap-carousel'
  = javascript_include_tag 'bootstrap-typeahead'
  = javascript_include_tag 'jquery'
  = javascript_include_tag 'application'

app/views/printers/index.html.haml
%div.container
  %h1 Printers

  %textarea#textfield.input-xlarge

  %p#replacement this is default text

/placed at the end of the document so the pages load quickly
= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'
= javascript_include_tag 'bootstrap'